services:
  database:
    image: docker.io/postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB_NAME
    ports:
      - 5432:5432
  admin:
    image: docker.io/adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  db-data: