[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api_shared = { path = "../api_shared" }
axum = { version = "0.6.0-rc.5", features = ["headers", "http2", "multipart"]}
axum-macros = "0.2.3"
thiserror = "1"
tokio = { version = "1", features = ["full"]}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
miette = { version = "5.4.1", features = ["fancy"] }

[dev-dependencies]
